Calc em and threshold
pln-fing-udelar/Mask-Align pull request #14
Opened 2022-04-28 18:07 UTC by sgoycoechea

2022-04-28 18:59 UTC, bryant1410 requested changes

2022-04-28 18:59 UTC, bryant1410 commented on scripts/calculate-threshold-and-em/calculate_em.py
> +import os
Remember to set the execution permissions to this file and the other ones. Also the shebang line (and to the other files):

```suggestion
#!/usr/bin/env python
import os
```

2022-04-28 18:59 UTC, bryant1410 commented on scripts/calculate-threshold-and-em/process_answer_indexes.py
> +    process_answer_indexes("./sentences.en", "./sentences.32k.en", "./answers_indexes.en", "./answers.en")
The "./" aren't necessary!

2022-04-28 18:59 UTC, bryant1410 commented on scripts/generate-alignments/generate_alignments.sh
> +../thualign/bin/generate.sh -s spanish -o output
In other parts of the code, there's the file `output.txt`. Is this fine?

2022-04-28 18:59 UTC, bryant1410 commented on scripts/generate-alignments/generate_alignments.sh
Don't make this file non-executable!

2022-04-29 13:56 UTC, sgoycoechea commented on scripts/generate-alignments/generate_alignments.sh
> +../thualign/bin/generate.sh -s spanish -o output
Yes, the extension is appended afterwards.

2022-05-04 22:17 UTC, bryant1410 approved these changes
I'm gonna fix the executable bit on the file after merging

2022-05-04 22:18 UTC, merged