Move the learning of the vocabulary to the setup part
pln-fing-udelar/Mask-Align pull request #15
Opened 2022-04-28 18:35 UTC by sgoycoechea

2022-04-28 18:53 UTC, bryant1410 requested changes
Looks good. Just one comment.

2022-04-28 18:53 UTC, bryant1410 commented on scripts/train-mask-align/preprocess_europarl.sh
> -cd corpus-es/
The `cd corpus-es/` should be kept, right?

2022-04-28 19:01 UTC, bryant1410 commented on README.md
> +Run the following script to download the [Europarl Spanish-English parallel corpus](https://www.statmt.org/europarl/v7/es-en.tgz), do some preprocessing, tokenize the sentences, and split the corpus:
Oh, also the download part should go in the Setup now, tight?

2022-04-28 19:02 UTC, bryant1410 commented on README.md
BTW, do you also wanna change the pretrained model URL for the one under an asset in the only release from the repo?

2022-04-29 13:49 UTC, sgoycoechea commented on scripts/train-mask-align/preprocess_europarl.sh
> -cd corpus-es/
It's in the setup script, so if they are following the steps they should already be in corpus-es/

Should we add it here anyways?

2022-04-29 13:49 UTC, sgoycoechea commented on README.md
> +Run the following script to download the [Europarl Spanish-English parallel corpus](https://www.statmt.org/europarl/v7/es-en.tgz), do some preprocessing, tokenize the sentences, and split the corpus:
Yes, because the vocabulary is learned from that corpus.

2022-04-29 13:57 UTC, bryant1410 commented on scripts/train-mask-align/preprocess_europarl.sh
> -cd corpus-es/
When you run a script, it doesn't leave your current fit changed if it changes internally. Unless you `source` it (or with `.`).

2022-04-29 13:58 UTC, bryant1410 commented on README.md
> +Run the following script to download the [Europarl Spanish-English parallel corpus](https://www.statmt.org/europarl/v7/es-en.tgz), do some preprocessing, tokenize the sentences, and split the corpus:
I mean to move the text i. The README to the setup part!

2022-04-29 14:02 UTC, sgoycoechea commented on README.md
> +Run the following script to download the [Europarl Spanish-English parallel corpus](https://www.statmt.org/europarl/v7/es-en.tgz), do some preprocessing, tokenize the sentences, and split the corpus:
Ohh right.

2022-05-04 14:17 UTC, sgoycoechea commented on README.md
Done

2022-05-04 22:14 UTC, bryant1410 approved these changes

2022-05-04 22:18 UTC, merged